spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/esmile
    username: root
    password: esmile

#  mvc:
#    static-path-pattern: /static/**
